package cs315.mvccardealership;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Date;

/**
 *
 * @author krist
 */
public class ModelServiceSchedule
{
    private double dblMileage;
    private String strServicePerformed;
    private Date dateDateOfService = new Date(); // Includes date and time.
    private Date dateDateNextServiceDue = new Date();
    private int intServiceID;
    private int intVehicleID;
    private int intServiceListID;

    /* Constructor that creates a service object that requires all data 
     * to be filled in. The ServiceID will be generated by the main class.
     */
    ModelServiceSchedule(double addMileage, String addServicePerformed,
            Date addNextServiceDue, Date addDateOfService,
            int addVehicleID, int addServiceID, int addServiceListID)
    {
        dblMileage = addMileage;
        strServicePerformed = addServicePerformed;
        dateDateNextServiceDue = addNextServiceDue;
        dateDateOfService = addDateOfService;
        intServiceID = addServiceID;
        intVehicleID = addVehicleID;
        intServiceListID = addServiceListID;

    }

    //Setters
    public void setMileage(double setMileage)
    {
        dblMileage = setMileage;
    }

    public void setServicePerformed(String setServicePerformed)
    {
        strServicePerformed = setServicePerformed;
    }

    public void setDateNextServiceDue(Date setDateNextServiceDue)
    {
        dateDateNextServiceDue = setDateNextServiceDue;
    }

    public void setDateOfService(Date setDateOfService)
    {
        dateDateOfService = setDateOfService;
    }

    public double getMileage()
    {
        return dblMileage;
    }

    public String getServicePerformed()
    {
        return strServicePerformed;
    }

    public Date getNextServiceDue()
    {
        return dateDateNextServiceDue;
    }

    public Date getDateOfService()
    {
        return dateDateOfService;
    }

    public int getServiceID()
    {
        return intServiceID;
    }

    public int getVehicleID()
    {
        return intVehicleID;
    }
    
    public int getServiceListID()
    {
        return intServiceListID;
    }
}
